[package]
name = "linked-lists"
version = "0.1.0"
authors = ["Keith Collister <hnefatl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
strum = "0.15.0"
strum_macros = "0.15.0"